### ISSUE TITLE
Pushing logs to st_output fails due to invalid number of arguments

### ISSUE THREAD

**Issue by Eder-K** [precice/systemtests#115]
Currently, when a systemtest triggered by an adapter attempts to push results to [precice_st_output](https://github.com/precice/precice_st_output), the push fails with an error message like in [this example](https://travis-ci.org/precice/systemtests/jobs/602015587#L564) (unwrap the push command if needed):

```bash
$ python push.py -s -t dealii-of
Cloning into '[secure]_st_output'...
EXECUTING: git clone https://github.com/[secure]/[secure]_st_output
EXECUTING: mkdir -p /home/travis/build/[secure]/systemtests/[secure]_st_output/Ubuntu1604.home
Traceback (most recent call last):
  File "push.py", line 161, in <module>
    add_job_log(args.test, not args.success, log_dir)
  File "push.py", line 116, in add_job_log
    create_job_log(systest, log, failed)
  File "push.py", line 70, in create_job_log
    *_, adapter_name, _, adapter_job_id = job_that_triggered.split('/')
ValueError: not enough values to unpack (expected at least 3, got 1)
```
This was not always the case. In tests like [this one](https://travis-ci.org/precice/systemtests/jobs/580208199#L511) from two months ago the push succeeds.

What is supposed to happen is that first the `trigger_systemtests.py` script sends a request that replaces the commit message on systemtests.

https://github.com/precice/systemtests/blob/14ba7f61133053c5d9afcf1af31441555fb8dbf0/trigger_systemtests.py#L160

For example: `fenics systemtest. Triggered by https://travis-ci.org/precice/fenics-adapater/jobs/602072485`.

The requested build will run the test and then execute `push.py`, whereby the script extracts information from the commit message that came with the request

https://github.com/precice/systemtests/blob/14ba7f61133053c5d9afcf1af31441555fb8dbf0/push.py#L65-L73

In current tests, however, the commit message read by `push.py` did not get overwritten and is simply the latest commit on the systemtests branch that gets used, see [this log](https://travis-ci.org/precice/systemtests/jobs/602072738#L568) (the final push command prints the full commit it parses before crashing, which matches the commit message of the [last commit](https://github.com/precice/systemtests/commit/c9dd71d24bb0152c85e26971e192c1f219fbd707) to this branch).

Therefore, the string that gets parsed doesn't include a link to the adapter job, which causes the operation to fail due to too few `/`-delimited parts.

**Comment by Eder-K** [comment]
With the merging of #147, the overhauled pushing script no longer performs the variable unpacking that lead to this problem.
